#!/usr/bin/env bash
{
    printf '%s ' "$0"
    printf '%q ' "$@"
    printf '\n'
} >> pkg-config.log

: "${PREFIX:=prebuilts/$(uname -m)-apple-darwin}"
: "${PKG_CONFIG_LIBDIR:=$PREFIX/lib}"
: "${PKG_CONFIG_PATH:=$PREFIX/lib/pkgconfig}"

export PKG_CONFIG_LIBDIR PKG_CONFIG_PATH

"${REAL_PKG_CONFIG:-$(which pkg-config)}" --define-variable=PREFIX="$PREFIX" --static "$@"
