---
name: Build cmdlets with containers

on:
  push:
    paths:
      - ulib.sh
      - libs/**.u
      - .github/workflows/build-multi-arch.yml
      - .github/scripts/**
    branches:
      - main

  workflow_dispatch:
    inputs:
      cmdlets:
        type: string
        description: Which cmdlets to build

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    container: ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/builder:${{ matrix.builder }}
    strategy:
      matrix:
        runner:
          # for x86_64
          - ubuntu-latest
          # for aarch64
          #- macos-arm64
          - ubuntu-latest-arm
        builder:
          # for *-linux-gnu
          - ubuntu-22.04
          # for *-linux-musl
          - alpine-3

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build
        shell: bash
        run: |-
          export CL_ARTIFACTS="${{ vars.ARTIFACTS_REMOTE_USER }}@${{ vars.ARTIFACTS_REMOTE_HOST }}:${{ vars.ARTIFACTS_REMOTE_PORT }}:${{ vars.ARTIFACTS_REMOTE_PATH }}"
          export CL_ARTIFACTS_TOKEN="${{ secrets.ARTIFACTS_REMOTE_TOKEN }}"
          export CL_NOTIFY="${{ vars.NOTIFY_WEBHOOK }}${{ secrets.NOTIFY_TOKEN }}"
          export CL_MIRRORS="${{ vars.MIRRORS }}"

          ./.github/scripts/build.sh "${{ github.event.inputs.cmdlets }}"
