---
name: Build cmdlets on host

on:
  push:
    paths:
      - ulib.sh
      - libs/**.u
      - .github/workflows/build-host.yml
      - .github/scripts/**
    branches:
      - main

  workflow_dispatch:
    inputs:
      cmdlets:
        type: string
        description: Which cmdlets to build

jobs:
  build-on-host:
    runs-on: ${{ matrix.host }}
    strategy:
      matrix:
        host:
          - macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.READ_TOKEN }}
          fetch-depth: 2

      - name: Prepare
        shell: bash
        run: |
          echo "${{ vars.ARTIFACTS_REMOTE_USER }}@${{ vars.ARTIFACTS_REMOTE_HOST }}:${{ vars.ARTIFACTS_REMOTE_PORT }}:${{ vars.ARTIFACTS_REMOTE_PATH }}" > cl_artifacts
          echo "${{ vars.NOTIFY_WEBHOOK }}${{ secrets.NOTIFY_TOKEN }}" > cl_notify
          echo "${{ secrets.ARTIFACTS_REMOTE_TOKEN }}" > cl_ssh_token
          echo "${{ vars.MIRRORS }}" > cl_mirrors

          ./.github/scripts/prepare.sh "${{ github.event.inputs.cmdlets }}"

      - name: Build
        run: ./.github/scripts/build.sh
