---
name: Build cmdlets macos

on:
  push:
    paths:
      - Makefile
      - ulib.sh
      - libs/**.u
      - .github/workflows/build-macos.yml
    branches:
      - main

  workflows_dispatch: null

jobs:
  build-on-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout (main)
        uses: actions/checkout@v3
        with:
          # read only token
          token: ${{ secrets.READ_TOKEN }}
          fetch-depth: 2

      - name: Build (macos)
        shell: bash
        run: |
          pwd -P
          set -ex

          files=($(git show --pretty="" --name-only ${{ github.sha }} | grep -w "^libs")) || true
          for x in ${files[@]}; do
            x=$(basename ${x%.u})
            [[ "$x" =~ ^\. ]] && continue  ## ignored files
            cmdlets+=("$x")
          done
          [ -n "${cmdlets[*]}" ] || cmdlets=(zlib)

          make prepare-host

          export NJOBS=1
          export ULOGS=silent
          export UPKG_MIRROR=${{ vars.MIRRORS }}
          export USE_CCACHE=1
          export CCACHE_DIR="~/.cache/cmdlets/ccache"

          ret=0
          for x in "${cmdlets[@]}"; do
            make "$x" || ret=$?
          done

          exit $ret

      - name: Deploy
        if: ${{ vars.ARTIFACTS_REMOTE_HOST != '' }}
        shell: bash
        run: |
          set -e

          cat << EOF > ssh_id_rsa
          ${{ secrets.ARTIFACTS_REMOTE_TOKEN }}
          EOF
          chmod 0600 ssh_id_rsa

          remote="${{ vars.ARTIFACTS_REMOTE_USER }}@${{ vars.ARTIFACTS_REMOTE_HOST }}:${{ vars.ARTIFACTS_REMOTE_PATH }}"
          opt=(-e "ssh -p ${{ vars.ARTIFACTS_REMOTE_PORT }} -i ssh_id_rsa -o StrictHostKeyChecking=no" -avc)

          ret=0

          echo "*** rsync artifacts to remote ***" &&
          rsync "${opt[@]}" --exclude='packages.lst' prebuilts/ $remote/cmdlets/latest/ || ret=$?

          echo "*** rsync logs to remote ***" &&
          rsync "${opt[@]}" logs/ $remote/cmdlets/logs/ || ret=$?

          echo "*** rsync packages to remote ***" &&
          rsync "${opt[@]}" packages/ $remote/packages/ || ret=$?

          exit $ret

      - name: Notify on failure
        if: failure()
        shell: bash
        run: |-
          curl --version
          curl -vL ${{ vars.NOTIFY_WEBHOOK }} \
              -H 'Content-Type: application/json' \
              --data @<(cat <<EOF
              {
                "token": "${{ secrets.NOTIFY_TOKEN }}",
                "title": "${{ github.repository }} ${{ job.status }}",
                "text":  "$(git show --abbrev-commit -s ${{ github.sha }} | sed 's/$/\\n/g')"
              }
          EOF
              )
