---
name: Build cmdlets latest

on:
  push:
    paths:
      - libs/*.rules
      - libs/*/RULES
    branches:
      - main

  workflow_dispatch:
    inputs:
      cmdlets:
        type: string
        description: Which cmdlets to build

jobs:
  build-locally:
    runs-on: ${{ vars.LOCAL_MACHINE || 'ubuntu-latest' }}
    container:
      image: ${{ vars.LOCAL_BUILDER || '' }}
      options: --privileged
    if: ${{ vars.LOCAL_REGISTRY == 'lcr.io' && vars.LOCAL_MACHINE != '' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.COMMIT_TOKEN }}

      - name: Build
        uses: ./.github/actions/buildx
        with:
          cmdlets: ${{ github.event.inputs.cmdlets }}
          webhook: ${{ vars.NOTIFY_WEBHOOK }}${{ secrets.NOTIFY_TOKEN }}
          artifacts-remote: ${{ vars.ARTIFACTS_REMOTE_USER }}@${{ vars.ARTIFACTS_REMOTE_HOST }}:${{ vars.ARTIFACTS_REMOTE_PORT }}:${{ vars.ARTIFACTS_REMOTE_PATH }}
          artifacts-token: ${{ secrets.ARTIFACTS_REMOTE_TOKEN }}
          mirrors: ${{ vars.MIRRORS }}

  build:
    runs-on: ${{ matrix.machine }}
    container:
      image: ${{ matrix.builder }}
      options: --privileged
    strategy:
      fail-fast: false
      matrix:
        include:
          # for arm64-apple-darwin or x86_64-apple-darwin
          - target: arm64-apple-darwin
            machine: macos-arm64
          - target: x86_64-apple-darwin
            machine: macos-intel
          - target: x86_64-linux-gnu
            machine: ubuntu-latest
            builder: lcr.io/mtdcy/builder:ubuntu-latest
          - target: x86_64-linux-musl
            machine: ubuntu-latest
            builder: lcr.io/mtdcy/builder:ubuntu-latest
          - target: aarch64-linux-gnu
            machine: ubuntu-latest-arm
            builder: lcr.io/mtdcy/builder:ubuntu-latest
          - target: aarch64-linux-musl
            machine: ubuntu-latest-arm
            builder: lcr.io/mtdcy/builder:ubuntu-latest
          - target: x86_64-pc-cygwin
            machine: ubuntu-latest
            builder: lcr.io/mtdcy/builder:cygwin64-latest
    if: ${{ vars.LOCAL_REGISTRY == 'lcr.io' && vars.LOCAL_MACHINE == '' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build
        uses: ./.github/actions/buildx
        with:
          cmdlets: ${{ inputs.cmdlets }}
          target: ${{ matrix.target }}
          webhook: ${{ vars.NOTIFY_WEBHOOK }}${{ secrets.NOTIFY_TOKEN }}
          artifacts-remote: ${{ vars.ARTIFACTS_REMOTE_USER }}@${{ vars.ARTIFACTS_REMOTE_HOST }}:${{ vars.ARTIFACTS_REMOTE_PORT }}:${{ vars.ARTIFACTS_REMOTE_PATH }}
          artifacts-token: ${{ secrets.ARTIFACTS_REMOTE_TOKEN }}
          mirrors: ${{ vars.MIRRORS }}
