---
name: Check cmdlets.sh

on:
  push:
    paths:
      - cmdlets.sh
      - .github/workflows/cmdlets.yml
    branches:
      - main

  workflow_dispatch: null

jobs:
  check-cmdlist.sh:
    runs-on: ubuntu-latest
    steps:
      - name: Check cmdlets.sh
        shell: bash
        run: |
          set -x

          if curl --fail -o /dev/nul -sIL https://git.mtdcy.top/mtdcy/cmdlets; then
            bash -c "$(curl -fsSL http://git.mtdcy.top/mtdcy/cmdlets/raw/branch/main/cmdlets.sh)" install
          else
            bash -c "$(curl -fsSL https://raw.githubusercontent.com/mtdcy/cmdlets/main/cmdlets.sh)" install
          fi

          # cmdlet: xz
          cmdlets.sh install xz
          xz --version

          # library: libz.a
          cmdlets.sh library libz
          find . -name "prebuilts/*/lib/libz.a"
          find . -name "prebuilts/*/include/zlib.h"

          # applet: neovim
          cmdlets.sh install nvim
          nvim -V1 -v

      - name: Notify on failure
        if: failure()
        shell: bash
        run: |-
          curl --version
          curl -vL ${{ vars.NOTIFY_WEBHOOK }} \
              -H 'Content-Type: application/json' \
              --data @<(cat <<EOF
              {
                "token": "${{ secrets.NOTIFY_TOKEN }}",
                "title": "${{ github.repository }} ${{ job.status }}",
                "text":  "$(git show --abbrev-commit -s ${{ github.sha }} | sed 's/$/\\n/g')"
              }
          EOF
              )
