---
name: Check cmdlets installer

on:
  push:
    paths:
      - cmdlets.sh
      - .github/workflows/cmdlets.yml
    branches:
      - main

  workflow_dispatch: null

jobs:
  install:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner:
          - ubuntu-latest
          - macos-latest

    steps:
      - name: Install cmdlets.sh
        shell: bash
        run: |
          export PATH="$HOME/.local/bin:/usr/bin:/bin"

          if curl --fail --connect-timeout 3 -o /dev/null -sIL https://git.mtdcy.top/mtdcy/cmdlets; then
            bash -ex -c "$(curl -fsSL http://git.mtdcy.top/mtdcy/cmdlets/raw/branch/main/cmdlets.sh)" install
          else
            bash -ex -c "$(curl -fsSL https://raw.githubusercontent.com/mtdcy/cmdlets/main/cmdlets.sh)" install
          fi

          echo "$PATH" >> $GITHUB_PATH

      - name: Test cmdlets.sh
        shell: bash
        run: |
          set -ex
          export PATH="$HOME/.local/bin:/usr/bin:/bin"

          which cmdlets.sh
          pushd "$(which cmdlets.sh | xargs dirname)"

          # 1 - cmdlets
          # 1.1
          cmdlets.sh install minigzip
          find prebuilts/bin/minigzip
          ls -l minigzip

          cmdlets.sh ls | grep " minigzip -"
          rm -rf minigzip prebuilts

          # 1.2
          cmdlets.sh install zlib/minigzip:minigzip
          find prebuilts/bin/minigzip
          ls -l minigzip

          cmdlets.sh ls | grep " zlib/minigzip - 1.3.1"
          rm -rf minigzip prebuilts

          # 1.3
          cmdlets.sh install minigzip@1.3.1:minigzip
          find prebuilts/bin/minigzip
          ls -l minigzip

          cmdlets.sh ls | grep " minigzip@1.3.1 - 1.3.1"
          rm -rf minigzip prebuilts

          # 1.4
          cmdlets.sh install zlib/minigzip@1.3.1:minigzip
          find prebuilts/bin/minigzip
          ls -l minigzip

          cmdlets.sh ls | grep " zlib/minigzip@1.3.1 - 1.3.1"
          rm -rf minigzip prebuilts

          # 2 - package
          # 2.1
          cmdlets.sh package zlib
          find prebuilts/bin/minigzip
          find prebuilts/lib/libz.a
          find prebuilts/include/zlib.h
          rm -rf prebuilts

          # 2.2
          cmdlets.sh package zlib@1.3.1
          find prebuilts/bin/minigzip
          find prebuilts/lib/libz.a
          find prebuilts/include/zlib.h
          rm -rf prebuilts

          # v3: versioned pkgfile
          latest=5.3
          versioned() {
            cmdlets.sh install $1@${2:-$latest}:$1
            ./$1 --version | grep -w "${2:-$latest}" || return 1
          }
          versioned bash 3.2
          versioned bash 4.4
          versioned bash

      - name: Notify on failure
        if: ${{ failure() && vars.NOTIFY_WEBHOOK != '' }}
        shell: bash
        run: |-
          curl --version
          curl -vL ${{ vars.NOTIFY_WEBHOOK }} \
              -H 'Content-Type: application/json' \
              --data @<(cat <<EOF
              {
                "token": "${{ secrets.NOTIFY_TOKEN }}",
                "title": "${{ github.repository }} ${{ job.status }}",
                "text":  "$(git show --abbrev-commit -s ${{ github.sha }} | sed 's/$/\\n/g')"
              }
          EOF
              )
